### ISSUE TITLE
Messung manuell auslösen

### ISSUE THREAD

**Issue by RasputinBerry** [jp112sdl/HB-UNI-Sen-DIST-TOF#1]
Hallo jp112sdl,

ich würde gern eine Messung zu einer bestimmten Zeit oder einem anderen Ereignis auslösen. 
Also unabhängig von dem einstellbaren Sendeintervall.
Geht das (ggf. zukünftig) ?

**Comment by jp112sdl** [comment]
Hi,

sowas wie ein Zeitprofil ist definitiv nicht vorgesehen.

Das einzige, was sich relativ leicht umsetzen ließe, wäre das Auslösen einer Messung mittels Taster.

**Comment by RasputinBerry** [comment]
Danke für die schnelle Reaktion. 
Ich entnehme der Antwort, dass ich die Frage eventuell missverständlich formuliert habe ... 

Ich würde gern eine manuelle Messung z.B. im ioBroker-Blockly (bevorzugt) oder in einem RaspMatic-Programm (geht auch) auslösen. Da gibts doch diese, für mich bis heute unverständlichen, "dom.GetObject ..."-Befehle oder so ...

Wie würde denn "Auslösen einer Messung mittels Taster" funktionieren ? Ein PIN auf GND oder so ?

Danke für die Nachhilfe.

**Comment by jp112sdl** [comment]
> Ich würde gern eine manuelle Messung z.B. im ioBroker-Blockly (bevorzugt) oder in einem RaspMatic-Programm (geht auch) auslösen.

Grundsätzlich ist es so, dass Sensoren nicht per Funk geweckt werden können.
Das Funkmodul "hört" also nie auf Funktelegramme.

> Wie würde denn "Auslösen einer Messung mittels Taster" funktionieren ? Ein PIN auf GND oder so ?

Ja. Codeseitig müsste das natürlich noch im Sketch erst eingebaut werden. Das ist so nicht vorgesehen.

**Comment by RasputinBerry** [comment]
> Codeseitig müsste das natürlich noch im Sketch erst eingebaut werden

... klar.... aber da würde ich mit meinen "Arduino-Blinklicht-20-Zeilen-Code"-Erfahrungen kläglich scheitern.
Wäre der Aufwand für Dich überschaubar und würdest Du das erl. ?
Oder gibt es einen Verweis von dem ich "abschreiben" könnte ?

Vielen Dank soweit, egal wie deine Antwort ausfällt.

**Comment by jp112sdl** [comment]
Hab es nur mal schnell  zusammengeschrieben, nicht getestet (Taster an Pin 9 / GND):
https://github.com/jp112sdl/HB-UNI-Sen-DIST-TOF/blob/dev_manual_measure/HB-UNI-Sen-DIST-TOF.ino

**Comment by RasputinBerry** [comment]
Vielen Dank ! Ich probiere es aus und melde mich.

Edit: 
Ich nutze zum ausprobieren die Platine HB-UNI-SEN-BATT. 
Dort ist lt. Schaltplan PIN 9 nicht, aber u.a. "Digital PIN 14" als Steckplatz "A0" rausgeführt. 
Wenn ich also im Sketch "9" durch "14" ersetze spare ich mir den Lötkolben.
Geht das (so einfach) ?

Edit:
Ja, geht so einfach ... ;-)) klappt einwandfrei.

Vielen Dank !
